language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t no7wataru/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true no7wataru/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "yoshioka-docker-react"
  env: "YoshiokaDockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-484882468786"
  bucket_path: "yoshioka-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
